cors:
  origenPatterns: http://localhost:8080,http://localhost:8081,https://erudio.com.br
security:
  jwt:
    token:
      secret-key: 53cr37
      expired-lenght: 3600000
springdoc:
  paths-to-match: 
    - /auth/**
    - /api/**/v**/**
  swagger-ui:
    use-root-path: true
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/financial_control?autoReconnect=true
    username: postgres
    password: postgre2023
  jpa: 
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: false
